export const PERMISSIONS = {
  USER_LIST: "USER_LIST",
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DEACTIVATE: "USER_DEACTIVATE",
  ROLE_LIST: "ROLE_LIST",
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",
  USER_ASSIGN_ROLE: "USER_ASSIGN_ROLE",
  USER_MANAGE_OVERRIDES: "USER_MANAGE_OVERRIDES",
  USER_MANAGE_BOOK_SCOPE: "USER_MANAGE_BOOK_SCOPE",
  BOOK_LIST: "BOOK_LIST",
  BOOK_VIEW: "BOOK_VIEW",
  BOOK_CREATE: "BOOK_CREATE",
  BOOK_UPDATE: "BOOK_UPDATE",
  BOOK_DELETE: "BOOK_DELETE",
  BOOK_MANAGE_ACCESS: "BOOK_MANAGE_ACCESS",
  CHAPTER_LIST: "CHAPTER_LIST",
  CHAPTER_VIEW: "CHAPTER_VIEW",
  CHAPTER_CREATE: "CHAPTER_CREATE",
  CHAPTER_UPDATE: "CHAPTER_UPDATE",
  CHAPTER_DELETE: "CHAPTER_DELETE",
  CHAPTER_CLAIM: "CHAPTER_CLAIM",
  CHAPTER_UNCLAIM: "CHAPTER_UNCLAIM",
  CHAPTER_ASSIGN: "CHAPTER_ASSIGN",
  CHAPTER_CHANGE_STATUS: "CHAPTER_CHANGE_STATUS",
  CHAPTER_EDIT_ANY: "CHAPTER_EDIT_ANY",
  CHAPTER_VIEW_ANY: "CHAPTER_VIEW_ANY",
  CHAPTER_EDIT_OWN: "CHAPTER_EDIT_OWN",
  CHAPTER_VIEW_OWN: "CHAPTER_VIEW_OWN",
  DASHBOARD_ADMIN: "DASHBOARD_ADMIN",
  DASHBOARD_MANAGER: "DASHBOARD_MANAGER",
  DASHBOARD_TRANSLATOR: "DASHBOARD_TRANSLATOR",
  REPORTS_VIEW: "REPORTS_VIEW",
} as const;

export const PERMISSION_GROUPS = {
  users: "کاربران و نقش‌ها",
  books: "کتاب‌ها",
  chapters: "چپترها",
  dashboard: "داشبورد",
  reports: "گزارش‌ها",
};

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATALOG: {
  key: PermissionKey;
  labelFa: string;
  group: keyof typeof PERMISSION_GROUPS;
}[] = [
  { key: PERMISSIONS.USER_LIST, labelFa: "مشاهده لیست کاربران", group: "users" },
  { key: PERMISSIONS.USER_VIEW, labelFa: "مشاهده جزئیات کاربر", group: "users" },
  { key: PERMISSIONS.USER_CREATE, labelFa: "ایجاد کاربر", group: "users" },
  { key: PERMISSIONS.USER_UPDATE, labelFa: "ویرایش کاربر", group: "users" },
  { key: PERMISSIONS.USER_DEACTIVATE, labelFa: "غیرفعال‌سازی کاربر", group: "users" },
  { key: PERMISSIONS.ROLE_LIST, labelFa: "مشاهده لیست نقش‌ها", group: "users" },
  { key: PERMISSIONS.ROLE_VIEW, labelFa: "مشاهده نقش", group: "users" },
  { key: PERMISSIONS.ROLE_CREATE, labelFa: "ایجاد نقش", group: "users" },
  { key: PERMISSIONS.ROLE_UPDATE, labelFa: "ویرایش نقش", group: "users" },
  { key: PERMISSIONS.ROLE_DELETE, labelFa: "حذف نقش", group: "users" },
  { key: PERMISSIONS.USER_ASSIGN_ROLE, labelFa: "تخصیص نقش به کاربر", group: "users" },
  {
    key: PERMISSIONS.USER_MANAGE_OVERRIDES,
    labelFa: "مدیریت دسترسی‌های خاص کاربر",
    group: "users",
  },
  {
    key: PERMISSIONS.USER_MANAGE_BOOK_SCOPE,
    labelFa: "مدیریت محدوده کتاب‌های کاربر",
    group: "users",
  },
  { key: PERMISSIONS.BOOK_LIST, labelFa: "مشاهده لیست کتاب‌ها", group: "books" },
  { key: PERMISSIONS.BOOK_VIEW, labelFa: "مشاهده کتاب", group: "books" },
  { key: PERMISSIONS.BOOK_CREATE, labelFa: "ایجاد کتاب", group: "books" },
  { key: PERMISSIONS.BOOK_UPDATE, labelFa: "ویرایش کتاب", group: "books" },
  { key: PERMISSIONS.BOOK_DELETE, labelFa: "حذف کتاب", group: "books" },
  {
    key: PERMISSIONS.BOOK_MANAGE_ACCESS,
    labelFa: "مدیریت دسترسی کتاب",
    group: "books",
  },
  { key: PERMISSIONS.CHAPTER_LIST, labelFa: "مشاهده لیست چپترها", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_VIEW, labelFa: "مشاهده چپتر", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_CREATE, labelFa: "ایجاد چپتر", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_UPDATE, labelFa: "ویرایش چپتر", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_DELETE, labelFa: "حذف چپتر", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_CLAIM, labelFa: "برداشتن چپتر", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_UNCLAIM, labelFa: "رها کردن چپتر", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_ASSIGN, labelFa: "تخصیص چپتر", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_CHANGE_STATUS, labelFa: "تغییر وضعیت چپتر", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_EDIT_ANY, labelFa: "ویرایش هر چپتر", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_VIEW_ANY, labelFa: "مشاهده هر چپتر", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_EDIT_OWN, labelFa: "ویرایش چپترهای خود", group: "chapters" },
  { key: PERMISSIONS.CHAPTER_VIEW_OWN, labelFa: "مشاهده چپترهای خود", group: "chapters" },
  { key: PERMISSIONS.DASHBOARD_ADMIN, labelFa: "داشبورد مدیر کل", group: "dashboard" },
  { key: PERMISSIONS.DASHBOARD_MANAGER, labelFa: "داشبورد مدیر پروژه", group: "dashboard" },
  { key: PERMISSIONS.DASHBOARD_TRANSLATOR, labelFa: "داشبورد مترجم", group: "dashboard" },
  { key: PERMISSIONS.REPORTS_VIEW, labelFa: "مشاهده گزارش‌ها", group: "reports" },
];

export const ALL_PERMISSION_KEYS = PERMISSION_CATALOG.map((item) => item.key);
